#!/usr/bin/env bash

. "$(dirname "$0")"/.nnn-plugin-helper

CTX=0
LIST="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/bookmarks"

if ! type fzf >/dev/null 2>&1; then
  printf "fzf missing"
  read -r _
  exit 1
fi

if ! type fd >/dev/null 2>&1; then
  printf "fd missing"
  read -r _
  exit 1
fi

RL_CMD="readlink"
if [ "$(uname)" == "Darwin" ]; then
  RL_CMD="greadlink"
fi

# check if LIST exists
if [ -n "$LIST" ]; then
  bookmarks=()
  # check if LIST contains any symlink file
  for s in "$LIST"/*; do
    if [ -L "$s" ]; then
      bookmarks+=( "$($RL_CMD -f "$s")" )
    fi
  done

  targets=( "${bookmarks[@]}" )
  # check if folders is recursive
  for dirs in "${bookmarks[@]}"; do
    r_dirs=$(fd . "$dirs" -I --maxdepth 1 --type d --exclude .git --exclude node_modules)
    if [ -n "$r_dirs" ]; then
      while IFS= read -r line; do
        targets+=("$line")
      done <<< "$r_dirs"
    fi
  done

  # Sort the targets array
  IFS=$'\n' sorted=($(sort <<<"${targets[*]}")); unset IFS

  # Get selection with FZF
  sel=$(printf "%s\n" "${sorted[@]}" | fzf --tac --no-info)
fi

if [ -n "$sel" ]; then
 nnn_cd "$sel" "$CTX"
fi
